apiVersion: v1
kind: Service
metadata:
    name: nfs-finance-service
    namespace: default
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
    selector:
        name: nfs-finance
