apiVersion: apps/v1
kind: Deployment
metadata:
    name: nfs-server
spec:
    replicas: 1
    selector:
        matchLabels:
            role: nfs-server
    template:
        metadata:
            labels:
                role: nfs-server
        spec:
            securityContext:
                fsGroup: 65533
            containers:
                - name: nfs-server
                  image: k8s.gcr.io/volume-nfs:0.8
                  ports:
                      - name: nfs
                        containerPort: 2049
                        protocol: TCP
                      - name: mountd
                        containerPort: 20048
                        protocol: TCP
                      - name: rpcbind
                        containerPort: 111
                        protocol: TCP
                  securityContext:
                      privileged: true
                  resources:
                      limits:
                          cpu: 100m
                          memory: 1Gi
                      requests:
                          cpu: 100m
                          memory: 1Gi
                  volumeMounts:
                      - mountPath: /exports
                        name: mypvc
            volumes:
                - name: mypvc
                  gcePersistentDisk:
                      pdName: lifemastery-nfs-disk
                      fsType: ext4
