apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        server: nfs-server.default.svc.cluster.local
        path: '/'
    mountOptions:
        - nfsvers=4.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: nfs
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: ''
    resources:
        requests:
            storage: 1Gi
    volumeName: nfs
